import { useState } from "react";
import { FileText, Sparkles, Lightbulb, Loader2, ClipboardCopy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { sampleRawClinicianNotes } from "@/data/syntheticData";
import { toast } from "sonner";

const DocumentationAssistant = () => {
  const [inputNotes, setInputNotes] = useState(sampleRawClinicianNotes);
  const [structuredNote, setStructuredNote] = useState("");
  const [reasoning, setReasoning] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isExplaining, setIsExplaining] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleGenerateNote = async () => {
    if (!inputNotes.trim()) {
      toast.error("Please enter clinical notes first");
      return;
    }

    setIsGenerating(true);
    setReasoning("");
    
    // Simulate AI processing
    await new Promise((resolve) => setTimeout(resolve, 1500));
    
    const generatedNote = `**CLINICAL DOCUMENTATION**
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Chief Complaint**
Patient presents with increased thirst, frequent urination, and fatigue over the past 3 weeks.

**History of Present Illness**
The patient reports poor adherence to prescribed Metformin regimen, having missed several doses over the past month. Current blood pressure reading is 148/92 mmHg, indicating mild elevation. Most recent HbA1c was 8.9%, indicating suboptimal glycemic control. No signs of acute distress observed during examination.

**Assessment**
1. Type 2 Diabetes Mellitus, uncontrolled (E11.65)
2. Essential Hypertension (I10)

**Plan**
1. Increase Metformin dosage with patient education on medication adherence
2. Order repeat HbA1c to monitor glycemic control
3. Schedule follow-up appointment in 3 months
4. Reinforce lifestyle modifications including diet and exercise

**Clinical Notes**
Patient demonstrates understanding of treatment plan. Will monitor blood glucose levels at home. Return precautions discussed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
*Generated by NextGenEHR AI Documentation Assistant*`;

    setStructuredNote(generatedNote);
    setIsGenerating(false);
    toast.success("Structured note generated successfully");
  };

  const handleExplainReasoning = async () => {
    if (!structuredNote) {
      toast.error("Generate a structured note first");
      return;
    }

    setIsExplaining(true);
    
    await new Promise((resolve) => setTimeout(resolve, 1000));
    
    const explanationText = `**AI Reasoning Process**

📋 **Input Analysis**
The raw notes contained abbreviated clinical terminology (c/o, x, dx, htn, t2dm) and informal documentation style typical of quick clinical entries.

🔄 **Transformation Steps**
1. Expanded medical abbreviations to standard terminology
2. Organized content into SOAP-aligned structure (Subjective, Objective, Assessment, Plan)
3. Added appropriate ICD-10 code references for diagnosed conditions
4. Ensured all clinical findings are documented with specificity

✅ **Quality Checks Applied**
• Chief complaint clearly stated
• HPI includes timeline and relevant history
• Assessment includes proper diagnosis codes
• Plan is actionable and complete
• Medical necessity established for billing`;

    setReasoning(explanationText);
    setIsExplaining(false);
  };

  const handleCopy = async () => {
    if (structuredNote) {
      await navigator.clipboard.writeText(structuredNote);
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleLoadSample = () => {
    setInputNotes(sampleRawClinicianNotes);
    toast.info("Sample notes loaded");
  };

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="p-6 border-b border-border bg-card">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
            <FileText className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h2 className="text-xl font-semibold text-foreground">
              AI Clinical Documentation Assistant
            </h2>
            <p className="text-sm text-muted-foreground">
              Transform raw clinician notes into structured clinical documentation
            </p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 p-6 overflow-y-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input Panel */}
          <Card className="flex flex-col">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base font-medium">Raw Clinical Notes</CardTitle>
                <Button variant="ghost" size="sm" onClick={handleLoadSample}>
                  Load Sample
                </Button>
              </div>
            </CardHeader>
            <CardContent className="flex-1 flex flex-col">
              <Textarea
                value={inputNotes}
                onChange={(e) => setInputNotes(e.target.value)}
                placeholder="Paste or type raw clinician notes here..."
                className="flex-1 min-h-[300px] resize-none font-mono text-sm"
              />
              <div className="mt-4 flex gap-3">
                <Button
                  onClick={handleGenerateNote}
                  disabled={isGenerating}
                  className="flex-1"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4 mr-2" />
                      Generate Structured Note
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Output Panel */}
          <Card className="flex flex-col">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base font-medium">Structured Output</CardTitle>
                {structuredNote && (
                  <Button variant="ghost" size="sm" onClick={handleCopy}>
                    {copied ? (
                      <Check className="w-4 h-4 mr-1" />
                    ) : (
                      <ClipboardCopy className="w-4 h-4 mr-1" />
                    )}
                    {copied ? "Copied" : "Copy"}
                  </Button>
                )}
              </div>
            </CardHeader>
            <CardContent className="flex-1 flex flex-col">
              <div className="flex-1 bg-secondary/30 rounded-lg p-4 overflow-y-auto min-h-[300px]">
                {structuredNote ? (
                  <pre className="whitespace-pre-wrap text-sm text-foreground font-sans leading-relaxed">
                    {structuredNote}
                  </pre>
                ) : (
                  <div className="h-full flex items-center justify-center text-muted-foreground">
                    <div className="text-center">
                      <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
                      <p>Generated note will appear here</p>
                    </div>
                  </div>
                )}
              </div>
              {structuredNote && (
                <div className="mt-4">
                  <Button
                    variant="outline"
                    onClick={handleExplainReasoning}
                    disabled={isExplaining}
                    className="w-full"
                  >
                    {isExplaining ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Analyzing...
                      </>
                    ) : (
                      <>
                        <Lightbulb className="w-4 h-4 mr-2" />
                        Explain Reasoning
                      </>
                    )}
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Reasoning Panel */}
        {reasoning && (
          <Card className="mt-6 animate-fade-in">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-medium flex items-center gap-2">
                <Lightbulb className="w-4 h-4 text-warning" />
                AI Reasoning
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-accent/50 rounded-lg p-4">
                <pre className="whitespace-pre-wrap text-sm text-foreground font-sans leading-relaxed">
                  {reasoning}
                </pre>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default DocumentationAssistant;
