import { useState } from "react";
import { FileText, Sparkles, Lightbulb, Loader2, ClipboardCopy, Check, Save, History, FolderOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { syntheticPatient } from "@/data/syntheticData";
import { useClinicalNotes } from "@/hooks/useClinicalNotes";
import { toast } from "sonner";
import NotesHistory from "./NotesHistory";
import PatientSelectDialog from "./PatientSelectDialog";

const DocumentationAssistant = () => {
  const [inputNotes, setInputNotes] = useState("");
  const [structuredNote, setStructuredNote] = useState("");
  const [reasoning, setReasoning] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isExplaining, setIsExplaining] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [showPatientSelect, setShowPatientSelect] = useState(false);
  const [selectedPatientId, setSelectedPatientId] = useState<string | null>(null);

  const { saveNote } = useClinicalNotes();

  const handlePatientSelect = (patientId: string, notes: string) => {
    setInputNotes(notes);
    setSelectedPatientId(patientId);
    toast.success(`Loaded notes for ${patientId}`);
  };

  const generateStructuredNote = (rawNotes: string): string => {
    // Parse the raw notes to extract key information
    const lines = rawNotes.split('\n').filter(line => line.trim());
    
    // Extract chief complaint (usually first line or after "c/o" or "cc:")
    const ccMatch = rawNotes.match(/(?:c\/o|cc:|chief complaint:?)\s*(.+)/i);
    const chiefComplaint = ccMatch ? ccMatch[1].trim() : lines[0] || "Not documented";
    
    // Extract vitals if present
    const bpMatch = rawNotes.match(/(?:bp|blood pressure):?\s*(\d+\/\d+)/i);
    const hrMatch = rawNotes.match(/(?:hr|heart rate|pulse):?\s*(\d+)/i);
    const tempMatch = rawNotes.match(/(?:temp|temperature):?\s*([\d.]+)/i);
    
    // Extract diagnoses/conditions
    const diabetesMatch = rawNotes.match(/(?:t2dm|type 2 diabetes|diabetes|dm2)/i);
    const htnMatch = rawNotes.match(/(?:htn|hypertension|high blood pressure)/i);
    const copdMatch = rawNotes.match(/(?:copd|chronic obstructive)/i);
    const anxietyMatch = rawNotes.match(/(?:anxiety|gad)/i);
    const depressionMatch = rawNotes.match(/(?:depression|mdd)/i);
    
    // Build diagnoses and codes
    const diagnoses: { name: string; code: string }[] = [];
    if (diabetesMatch) diagnoses.push({ name: "Type 2 Diabetes Mellitus", code: "E11.65" });
    if (htnMatch) diagnoses.push({ name: "Essential Hypertension", code: "I10" });
    if (copdMatch) diagnoses.push({ name: "Chronic Obstructive Pulmonary Disease", code: "J44.9" });
    if (anxietyMatch) diagnoses.push({ name: "Generalized Anxiety Disorder", code: "F41.1" });
    if (depressionMatch) diagnoses.push({ name: "Major Depressive Disorder", code: "F32.9" });
    
    // Default if no specific conditions found
    if (diagnoses.length === 0) {
      diagnoses.push({ name: "General Medical Examination", code: "Z00.00" });
    }
    
    // Build vitals section
    const vitalsItems: string[] = [];
    if (bpMatch) vitalsItems.push(`Blood Pressure: ${bpMatch[1]} mmHg`);
    if (hrMatch) vitalsItems.push(`Heart Rate: ${hrMatch[1]} bpm`);
    if (tempMatch) vitalsItems.push(`Temperature: ${tempMatch[1]}°F`);
    
    const vitalsSection = vitalsItems.length > 0 
      ? vitalsItems.join('\n') 
      : "Vitals not documented in source notes";
    
    // Extract plan items
    const planMatch = rawNotes.match(/(?:plan|rx|tx|treatment):?\s*(.+)/i);
    const followUpMatch = rawNotes.match(/(?:f\/u|follow.?up|rtn):?\s*(.+)/i);
    
    const planItems: string[] = [];
    if (planMatch) planItems.push(planMatch[1].trim());
    if (followUpMatch) planItems.push(`Follow-up: ${followUpMatch[1].trim()}`);
    if (planItems.length === 0) planItems.push("Continue current management", "Schedule follow-up as needed");
    
    return `**CLINICAL DOCUMENTATION**
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Chief Complaint**
${chiefComplaint}

**History of Present Illness**
${lines.slice(0, 3).join('. ').replace(/\.\./g, '.')}

**Vitals**
${vitalsSection}

**Assessment**
${diagnoses.map((d, i) => `${i + 1}. ${d.name} (${d.code})`).join('\n')}

**Plan**
${planItems.map((p, i) => `${i + 1}. ${p}`).join('\n')}

**Clinical Notes**
Patient demonstrates understanding of treatment plan. Return precautions discussed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
*Generated by NextGenEHR AI Documentation Assistant*
*Patient ID: ${selectedPatientId || 'Unknown'}*`;
  };

  const handleGenerateNote = async () => {
    if (!inputNotes.trim()) {
      toast.error("Please enter clinical notes first");
      return;
    }

    setIsGenerating(true);
    setReasoning("");
    
    // Simulate AI processing
    await new Promise((resolve) => setTimeout(resolve, 1500));
    
    const generatedNote = generateStructuredNote(inputNotes);

    setStructuredNote(generatedNote);
    setIsGenerating(false);
    toast.success("Structured note generated successfully");
  };

  const handleExplainReasoning = async () => {
    if (!structuredNote) {
      toast.error("Generate a structured note first");
      return;
    }

    setIsExplaining(true);
    
    await new Promise((resolve) => setTimeout(resolve, 1000));
    
    const explanationText = `**AI Reasoning Process**

📋 **Input Analysis**
The raw notes contained abbreviated clinical terminology (c/o, x, dx, htn, t2dm) and informal documentation style typical of quick clinical entries.

🔄 **Transformation Steps**
1. Expanded medical abbreviations to standard terminology
2. Organized content into SOAP-aligned structure (Subjective, Objective, Assessment, Plan)
3. Added appropriate ICD-10 code references for diagnosed conditions
4. Ensured all clinical findings are documented with specificity

✅ **Quality Checks Applied**
• Chief complaint clearly stated
• HPI includes timeline and relevant history
• Assessment includes proper diagnosis codes
• Plan is actionable and complete
• Medical necessity established for billing`;

    setReasoning(explanationText);
    setIsExplaining(false);
  };

  const handleCopy = async () => {
    if (structuredNote) {
      await navigator.clipboard.writeText(structuredNote);
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleSaveNote = async () => {
    if (!structuredNote) {
      toast.error("Generate a note first");
      return;
    }

    setIsSaving(true);
    const { error } = await saveNote(
      syntheticPatient.patient_id,
      inputNotes,
      structuredNote,
      reasoning || undefined
    );

    if (error) {
      toast.error("Failed to save note");
    } else {
      toast.success("Note saved to your history");
    }
    setIsSaving(false);
  };

  const handleOpenPatientSelect = () => {
    setShowPatientSelect(true);
  };

  if (showHistory) {
    return <NotesHistory onBack={() => setShowHistory(false)} />;
  }

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="p-6 border-b border-border bg-card">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <FileText className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-semibold text-foreground">
                AI Clinical Documentation Assistant
              </h2>
              <p className="text-sm text-muted-foreground">
                Transform raw clinician notes into structured clinical documentation
              </p>
            </div>
          </div>
          <Button variant="outline" onClick={() => setShowHistory(true)}>
            <History className="w-4 h-4 mr-2" />
            View History
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 p-6 overflow-y-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input Panel */}
          <Card className="flex flex-col">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base font-medium">
                  Raw Clinical Notes
                  {selectedPatientId && (
                    <span className="ml-2 text-xs font-normal text-muted-foreground">
                      ({selectedPatientId})
                    </span>
                  )}
                </CardTitle>
                <Button variant="ghost" size="sm" onClick={handleOpenPatientSelect}>
                  <FolderOpen className="w-4 h-4 mr-1" />
                  Load Patient
                </Button>
              </div>
            </CardHeader>
            <CardContent className="flex-1 flex flex-col">
              <Textarea
                value={inputNotes}
                onChange={(e) => setInputNotes(e.target.value)}
                placeholder="Paste or type raw clinician notes here..."
                className="flex-1 min-h-[300px] resize-none font-mono text-sm"
              />
              <div className="mt-4 flex gap-3">
                <Button
                  onClick={handleGenerateNote}
                  disabled={isGenerating}
                  className="flex-1"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4 mr-2" />
                      Generate Structured Note
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Output Panel */}
          <Card className="flex flex-col">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base font-medium">Structured Output</CardTitle>
                <div className="flex gap-2">
                  {structuredNote && (
                    <>
                      <Button variant="ghost" size="sm" onClick={handleCopy}>
                        {copied ? (
                          <Check className="w-4 h-4 mr-1" />
                        ) : (
                          <ClipboardCopy className="w-4 h-4 mr-1" />
                        )}
                        {copied ? "Copied" : "Copy"}
                      </Button>
                      <Button variant="ghost" size="sm" onClick={handleSaveNote} disabled={isSaving}>
                        {isSaving ? (
                          <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                        ) : (
                          <Save className="w-4 h-4 mr-1" />
                        )}
                        Save
                      </Button>
                    </>
                  )}
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex-1 flex flex-col">
              <div className="flex-1 bg-secondary/30 rounded-lg p-4 overflow-y-auto min-h-[300px]">
                {structuredNote ? (
                  <pre className="whitespace-pre-wrap text-sm text-foreground font-sans leading-relaxed">
                    {structuredNote}
                  </pre>
                ) : (
                  <div className="h-full flex items-center justify-center text-muted-foreground">
                    <div className="text-center">
                      <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
                      <p>Generated note will appear here</p>
                    </div>
                  </div>
                )}
              </div>
              {structuredNote && (
                <div className="mt-4">
                  <Button
                    variant="outline"
                    onClick={handleExplainReasoning}
                    disabled={isExplaining}
                    className="w-full"
                  >
                    {isExplaining ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Analyzing...
                      </>
                    ) : (
                      <>
                        <Lightbulb className="w-4 h-4 mr-2" />
                        Explain Reasoning
                      </>
                    )}
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Reasoning Panel */}
        {reasoning && (
          <Card className="mt-6 animate-fade-in">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-medium flex items-center gap-2">
                <Lightbulb className="w-4 h-4 text-warning" />
                AI Reasoning
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-accent/50 rounded-lg p-4">
                <pre className="whitespace-pre-wrap text-sm text-foreground font-sans leading-relaxed">
                  {reasoning}
                </pre>
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      <PatientSelectDialog
        open={showPatientSelect}
        onOpenChange={setShowPatientSelect}
        onSelect={handlePatientSelect}
      />
    </div>
  );
};

export default DocumentationAssistant;
